import pygame

EXIT_GAME_EVENT = pygame.QUIT
START_GAME_EVENT = pygame.USEREVENT + 1
OPEN_MAIN_MENU_EVENT = pygame.USEREVENT + 2
LOADING_SCREEN_EVENT = pygame.USEREVENT + 3
OPEN_CONNECTION_MENU_EVENT = pygame.USEREVENT + 4
CONNECT_TO_SERVER_EVENT = pygame.USEREVENT + 5
START_SERVER_MENU_EVENT = pygame.USEREVENT + 6
OPEN_SETTINGS_MENU_EVENT = pygame.USEREVENT + 7
CHANGE_SOUND_MODE = pygame.USEREVENT + 8
CHANGE_MUSIC_MODE = pygame.USEREVENT + 9
CHANGE_MUSIC_SLIDER = pygame.USEREVENT + 10
CHANGE_SOUNDS_SLIDER = pygame.USEREVENT + 11

START_SERVER_AT_ADDRESS = pygame.USEREVENT + 50
KILL_SERVER = pygame.USEREVENT + 51

SHOW_GAME_STATISTICS = pygame.USEREVENT + 100
