import pygame

EXIT_GAME_EVENT = pygame.QUIT
START_GAME_EVENT = pygame.USEREVENT + 1
OPEN_MAIN_MENU_EVENT = pygame.USEREVENT + 2
LOADING_SCREEN_EVENT = pygame.USEREVENT + 3
OPEN_CONNECTION_MENU_EVENT = pygame.USEREVENT + 4
CONNECT_TO_SERVER_EVENT = pygame.USEREVENT + 5
START_SERVER_MENU_EVENT = pygame.USEREVENT + 6
SHOW_GAME_STATISTICS = pygame.USEREVENT + 100
